In [1]:
import numpy as np

In [9]:
A = np.zeros((10,10))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
for i in range(1, 10):
    for j in range(1,10):
        A[i][j] = 1/(1+(i/j))

In [16]:
print(A)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.5        0.66666667 0.75       0.8        0.83333333
  0.85714286 0.875      0.88888889 0.9       ]
 [0.         0.33333333 0.5        0.6        0.66666667 0.71428571
  0.75       0.77777778 0.8        0.81818182]
 [0.         0.25       0.4        0.5        0.57142857 0.625
  0.66666667 0.7        0.72727273 0.75      ]
 [0.         0.2        0.33333333 0.42857143 0.5        0.55555556
  0.6        0.63636364 0.66666667 0.69230769]
 [0.         0.16666667 0.28571429 0.375      0.44444444 0.5
  0.54545455 0.58333333 0.61538462 0.64285714]
 [0.         0.14285714 0.25       0.33333333 0.4        0.45454545
  0.5        0.53846154 0.57142857 0.6       ]
 [0.         0.125      0.22222222 0.3        0.36363636 0.41666667
  0.46153846 0.5        0.53333333 0.5625    ]
 [0.         0.11111111 0.2        0.27272727 0.33333333 0.38461538
  0.42857143 0.46666667 0.5     